com.github.hluk.copyq.json
=> Update to v3.6.0

com.github.hluk.copyq.json
=> Update to v3.6.1

com.github.hluk.copyq.json
=> Update to v3.7.0

com.github.hluk.copyq.json
=> Update to v3.7.1

com.github.hluk.copyq.json
=> Update to v3.7.3

com.github.hluk.copyq.json
=> Update to v3.8.0

0001-Add-required-tag-for-flatpak.patch, com.github.hluk.copyq.json
=> Update to v3.9.0

com.github.hluk.copyq.json
=> Update to v3.9.2

com.github.hluk.copyq.json
=> Bump KDE runtime to 5.12

com.github.hluk.copyq.json
=> Update to v3.9.3

com.github.hluk.copyq.json
=> Update to v3.10.0

com.github.hluk.copyq.json
=> Bump KDE runtime to 5.14

com.github.hluk.copyq.json
=> Update to v3.11.0

com.github.hluk.copyq.json
=> Update to v3.11.1

com.github.hluk.copyq.json
=> Update to v3.12.0

com.github.hluk.copyq.json
=> Update to v3.13.0

com.github.hluk.copyq.json
See: https://github.com/flathub/org.nextcloud.Nextcloud/pull/67
=> Fix tray icon

com.github.hluk.copyq.yaml
=> Fix item encryption

com.github.hluk.copyq.yaml
Fixes https://github.com/hluk/CopyQ/issues/2739
=> Bump the runtime version to 5.15-23.08

com.github.hluk.copyq.yaml
Fixes https://github.com/flathub-infra/flatpak-external-data-checker/issues/468
=> Fix tag pattern tag-pattern
